---
dependency:
  name: galaxy
# Lokale Dockerinstant wird aufgezogen um dort die Tests durchzuführen
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
# Platform die in Docker installiert werden soll
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
